apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: sample-persistent-volume
  name: data-pv-volume
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/msdata/data"